# Generated by Django 6.0 on 2026-03-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_brand_alter_products_is_active'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='menuitem',
            table_comment='Пункты главного меню сайта (связь с категорией и порядок отображения).',
        ),
        migrations.AlterModelTableComment(
            name='settings',
            table_comment='Глобальные настройки сайта (название, контакты, режим обслуживания и т.п.).',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(db_comment='Внешний ключ к таблице Categories', help_text='Категория, на которую ведёт этот пункт меню.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_url', to='products.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_active',
            field=models.BooleanField(db_comment='Флаг активности пункта меню.', default=True, help_text='Если выключено — пункт не отображается в меню.', verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(db_comment='Порядок сортировки пункта меню.', default=0, help_text='Порядок сортировки в меню (меньше — выше).', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(db_comment='Название пункта меню.', help_text='Текст, который будет показан в меню.', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(blank=True, db_comment='Контактный email сайта.', help_text='Контактный email, отображаемый на сайте.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_text',
            field=models.TextField(blank=True, db_comment='Текст, отображаемый в подвале сайта.', help_text='Произвольный текст для отображения в подвале сайта.', verbose_name='Текст в подвале'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_maintenance_mode',
            field=models.BooleanField(db_comment='Флаг режима обслуживания сайта.', default=False, help_text='Если включено — сайт может показывать страницу обслуживания.', verbose_name='Режим обслуживания'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_number',
            field=models.CharField(blank=True, db_comment='Контактный номер телефона сайта.', help_text='Контактный номер телефона, отображаемый на сайте.', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_logo',
            field=models.ImageField(blank=True, db_comment='Путь к файлу логотипа сайта (может быть NULL).', help_text='Файл логотипа, который отображается в шапке сайта.', null=True, upload_to='site_settings/', verbose_name='Логотип'),
        ),
    ]
