# Generated by Django 6.0 on 2026-03-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_menuitem_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, db_comment='Краткое описание сайта для отображения в шапке или других местах.', help_text='Краткое описание сайта для отображения в шапке или других местах.', verbose_name='Описание сайта'),
        ),
    ]
