# Generated by Django 5.0 on 2025-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='products_ca_title_e30f7f_idx')],
            },
        ),
    ]
