# Generated by Django 5.0 on 2025-05-27 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('thumbnail', models.ImageField(upload_to='%Y/%m/%d/thumbnails')),
                ('image_type', models.CharField(choices=[('main', 'Основное изображение'), ('secondary', 'Дополнительное'), ('thumbnail', 'Миниатюра')], default='secondary', max_length=10, verbose_name='Тип изображения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['title'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('male', 'мужские'), ('female', 'женские'), ('unisex', 'универсальные'), ('kids', 'детские')], default='unisex', max_length=10, verbose_name='Тип обуви'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='product_number',
            field=models.CharField(default=None, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['id', 'slug'], name='products_pr_id_2e4687_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['title'], name='products_pr_title_21cf2b_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['-created_at'], name='products_pr_created_6dc43e_idx'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products'),
        ),
    ]
