# Generated by Django 5.0 on 2025-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_images_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='params',
            field=models.TextField(default=''),
        ),
    ]
