# Generated by Django 5.0 on 2025-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_colors_sizes_store'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('color', 'size', 'product'), name='unique_variant_color_size_product'),
        ),
    ]
