# Generated by Django 6.0 on 2026-02-27 13:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_store_unique_variant_color_size_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['product', 'image_type'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'ordering': ['size'], 'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Остаток на складе', 'verbose_name_plural': 'Остатки на складе'},
        ),
        migrations.AlterModelTableComment(
            name='categories',
            table_comment='Таблица категорий товаров для группировки обуви по типам',
        ),
        migrations.AlterModelTableComment(
            name='colors',
            table_comment='Таблица доступных цветов обуви',
        ),
        migrations.AlterModelTableComment(
            name='images',
            table_comment='Таблица изображений товаров с поддержкой разных типов (основное, доп., миниатюра)',
        ),
        migrations.AlterModelTableComment(
            name='products',
            table_comment='Основная таблица товаров (обуви) с характеристиками и метаданными',
        ),
        migrations.AlterModelTableComment(
            name='sizes',
            table_comment='Таблица доступных размеров обуви (EUR)',
        ),
        migrations.AlterModelTableComment(
            name='store',
            table_comment='Таблица складского учета с остатками по цветам и размерам',
        ),
        migrations.AlterField(
            model_name='categories',
            name='desc',
            field=models.TextField(db_comment='Текстовое описание категории для SEO и отображения', default='', help_text='Краткое описание для SEO и отображения на странице категории', verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(db_comment='URL-идентификатор для формирования ЧПУ', default=None, help_text="Человекопонятный URL на основе названия (напр. 'krossovki-nike')", max_length=250, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(db_comment='Название категории товаров (уникальное)', help_text='Например: Кроссовки, Ботинки, Сандалии', max_length=250, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='title',
            field=models.CharField(db_comment='Название цвета обуви (уникальное)', help_text='Например: Красный, Синий, Черный', max_length=250, unique=True, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, db_comment='Путь к оригинальному файлу изображения', help_text='Оригинальное изображение товара', upload_to='%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_type',
            field=models.CharField(choices=[('main', 'Основное изображение'), ('secondary', 'Дополнительное'), ('thumbnail', 'Миниатюра')], db_comment='Тип изображения: main - основное, secondary - дополнительное, thumbnail - миниатюра', default='secondary', help_text='Назначение изображения (главное, дополнительное, миниатюра)', max_length=10, verbose_name='Тип изображения'),
        ),
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(db_comment='Внешний ключ к таблице Products', help_text='Товар, которому принадлежит изображение', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='images',
            name='thumbnail',
            field=models.ImageField(db_comment='Путь к файлу миниатюры изображения', help_text='Уменьшенная копия для списков товаров', upload_to='%Y/%m/%d/thumbnails', verbose_name='Миниатюра'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('new_balance', 'New Balance'), ('asics', 'ASICS'), ('under_armour', 'Under Armour'), ('skechers', 'Skechers'), ('gucci', 'Gucci'), ('prada', 'Prada'), ('louis_vuitton', 'Louis Vuitton'), ('balenciaga', 'Balenciaga'), ('dior', 'Dior'), ('vans', 'Vans'), ('converse', 'Converse'), ('timberland', 'Timberland'), ('dr_martens', 'Dr. Martens'), ('salomon', 'Salomon'), ('merrell', 'Merrell'), ('columbia', 'Columbia'), ('the_north_face', 'The North Face'), ('ralf_ringer', 'Ralf Ringer'), ('ecco', 'ECCO'), ('bugatti', 'Bugatti'), ('carlo_pazolini', 'Carlo Pazolini'), ('kapitoshka', 'Капитошка'), ('kotofey', 'Котофей'), ('antilopa', 'Антилопа'), ('bartek', 'Bartek')], db_comment='Код бренда производителя', default='nike', help_text='Производитель/бренд обуви', max_length=120, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(db_comment='Внешний ключ к таблице Categories', default=None, help_text='Категория к которой относится товар', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='country',
            field=models.CharField(choices=[('it', 'Италия'), ('de', 'Германия'), ('pt', 'Португалия'), ('es', 'Испания'), ('fr', 'Франция'), ('uk', 'Великобритания'), ('tr', 'Турция'), ('cn', 'Китай'), ('vn', 'Вьетнам'), ('in', 'Индия'), ('id', 'Индонезия'), ('jp', 'Япония'), ('kr', 'Южная Корея'), ('us', 'США'), ('br', 'Бразилия'), ('mx', 'Мексика'), ('ru', 'Россия'), ('by', 'Беларусь'), ('za', 'Южная Африка'), ('au', 'Австралия')], db_comment='Код страны производителя', default='ru', help_text='Страна, где произведен товар', max_length=32, verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(db_comment='Дата и время добавления товара в каталог', default=django.utils.timezone.now, help_text='Когда товар был добавлен в каталог', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(db_comment='Подробное текстовое описание товара', default='', help_text='Подробное описание, характеристики, особенности модели', verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.DecimalField(db_comment='Цена со скидкой (если применяется)', decimal_places=2, default=None, help_text='Акционная цена (если есть скидка)', max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('male', 'мужские'), ('female', 'женские'), ('unisex', 'универсальные'), ('kids', 'детские')], db_comment='Пол целевой аудитории (male/female/unisex/kids)', default='unisex', help_text='Для кого предназначена обувь', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(db_comment='Флаг активности товара (True - отображается на сайте)', default=False, help_text='Отображать товар на сайте или нет', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(db_comment='Регулярная цена товара (до 10 знаков, 2 знака после запятой)', decimal_places=2, default=None, help_text='Регулярная цена товара', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_number',
            field=models.CharField(db_comment='Уникальный артикул товара (SKU) для идентификации', default=None, help_text='Уникальный артикул товара (SKU)', max_length=250, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='products',
            name='season',
            field=models.CharField(choices=[('winter', 'зима'), ('summer', 'лето'), ('autumn', 'осень'), ('spring', 'весна'), ('spring-summer', 'весна-лето'), ('autumn-winter', 'осень-зима')], db_comment='Сезон для которого рекомендуется обувь', default='summer', help_text='Рекомендуемый сезон для носки', max_length=16, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(db_comment='URL-идентификатор для формирования ЧПУ страницы товара', default=None, help_text='Уникальный URL для страницы товара', max_length=250, verbose_name='URL-идентификатор'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sole_material',
            field=models.CharField(choices=[('tpr', 'Термопластичная резина (TPR)'), ('pu', 'Полиуретан (PU)'), ('eva', 'Этиленвинилацетат (EVA)'), ('rubber', 'Натуральный каучук/резина'), ('tpu', 'Термополиуретан (TPU)'), ('pvc', 'Поливинилхлорид (PVC)'), ('phylon', 'Файлон (Phylon)'), ('phylite', 'Файлайт (Phylite)'), ('compressed_rubber', 'Прессованная резина'), ('carbon', 'Карбоновая подошва'), ('microcellular', 'Микропористая резина'), ('crepe', 'Креповая подошва'), ('leather', 'Кожаная подошва'), ('combination', 'Комбинированная подошва')], db_comment='Код материала подошвы', default='rubber', help_text='Материал из которого сделана подошва', max_length=20, verbose_name='Материал подошвы'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(db_comment='Полное название модели обуви (уникальное)', default='', help_text='Полное название модели обуви', max_length=250, unique=True, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Дата и время последнего обновления информации о товаре', help_text='Когда информация о товаре обновлялась последний раз', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='products',
            name='upper_material',
            field=models.CharField(choices=[('leather', 'Натуральная кожа'), ('suede', 'Замша'), ('nubuck', 'Нубук'), ('textile', 'Текстиль'), ('mesh', 'Сетка (дышащий материал)'), ('synthetic', 'Искусственная кожа'), ('knit', 'Вязаный материал'), ('thermo', 'Термополиуретан (TPU)'), ('rubber', 'Резина/каучук'), ('pu', 'Полиуретан (PU)'), ('eva', 'Этиленвинилацетат (EVA)'), ('neoprene', 'Неопрен'), ('goretex', 'Мембрана Gore-Tex'), ('elastic', 'Эластичные материалы'), ('combination', 'Комбинированные материалы')], db_comment='Код материала верха обуви', default='leather', help_text='Материал из которого сделан верх обуви', max_length=20, verbose_name='Материал верха'),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.SmallIntegerField(db_comment='Вес товара в граммах для расчета стоимости доставки', default=0, help_text='Вес товара в граммах (для расчета доставки)', verbose_name='Вес (граммы)'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.SmallIntegerField(db_comment='Размер обуви по европейской сетке (уникальный)', help_text='Размер по европейской сетке (EUR)', unique=True, verbose_name='Размер обуви'),
        ),
        migrations.AlterField(
            model_name='store',
            name='cnt',
            field=models.SmallIntegerField(db_comment='Доступное количество единиц товара на складе (только > 0)', help_text='Доступное количество на складе (только положительное число)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='store',
            name='color',
            field=models.ForeignKey(db_comment='Внешний ключ к таблице Colors (может быть NULL)', help_text='Цвет данного экземпляра товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='products.colors', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product',
            field=models.ForeignKey(db_comment='Внешний ключ к таблице Products', default=None, help_text='Связанный товар', on_delete=django.db.models.deletion.CASCADE, related_name='store', to='products.products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.ForeignKey(db_comment='Внешний ключ к таблице Sizes (может быть NULL)', help_text='Размер данного экземпляра товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='products.sizes', verbose_name='Размер'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product', 'image_type'], name='products_im_product_4f71a1_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['brand'], name='products_pr_brand_a07c30_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category'], name='products_pr_categor_21914c_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['product', 'color', 'size'], name='products_st_product_0d92e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('cnt__gt', 0)), name='cnt_positive', violation_error_message='Количество товара должно быть положительным'),
        ),
        migrations.AlterConstraint(
            model_name='store',
            name='unique_variant_color_size_product',
            constraint=models.UniqueConstraint(fields=('color', 'size', 'product'), name='unique_variant_color_size_product', violation_error_message='Такая комбинация цвета, размера и товара уже существует'),
        ),
    ]
