# Generated by Django 6.0 on 2026-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_categories_options_alter_colors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('new_balance', 'New Balance'), ('asics', 'ASICS'), ('under_armour', 'Under Armour'), ('skechers', 'Skechers'), ('demix', 'Demix'), ('gucci', 'Gucci'), ('prada', 'Prada'), ('louis_vuitton', 'Louis Vuitton'), ('balenciaga', 'Balenciaga'), ('dior', 'Dior'), ('vans', 'Vans'), ('converse', 'Converse'), ('timberland', 'Timberland'), ('dr_martens', 'Dr. Martens'), ('salomon', 'Salomon'), ('merrell', 'Merrell'), ('columbia', 'Columbia'), ('the_north_face', 'The North Face'), ('ralf_ringer', 'Ralf Ringer'), ('ecco', 'ECCO'), ('bugatti', 'Bugatti'), ('carlo_pazolini', 'Carlo Pazolini'), ('kapitoshka', 'Капитошка'), ('kotofey', 'Котофей'), ('antilopa', 'Антилопа'), ('bartek', 'Bartek')], db_comment='Код бренда производителя', default='nike', help_text='Производитель/бренд обуви', max_length=120, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.BooleanField(db_comment='Флаг для отображения товара (True - отображается на сайте)', default=False, help_text='Отображать товар на сайте или нет', verbose_name='Активен'),
        ),
    ]
