# Generated by Django 5.0 on 2026-01-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название конфигурации"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "Верхняя панель"),
                            ("left", "Левая боковая панель"),
                            ("right", "Правая боковая панель"),
                            ("bottom", "Нижняя панель"),
                            ("modal", "Модальное окно"),
                        ],
                        default="top",
                        max_length=10,
                        verbose_name="Расположение панели",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "placeholder",
                    models.CharField(
                        default="Поиск...",
                        max_length=200,
                        verbose_name="Подсказка в поле",
                    ),
                ),
                (
                    "show_results_count",
                    models.BooleanField(
                        default=True, verbose_name="Показывать кол-во результатов"
                    ),
                ),
                (
                    "results_limit",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Лимит результатов"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип объекта для поиска",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация поиска",
                "verbose_name_plural": "Конфигурации поиска",
            },
        ),
        migrations.CreateModel(
            name="SearchField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        max_length=100, verbose_name="Название поля в модели"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=100, verbose_name="Отображаемое название"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Текстовое поле"),
                            ("checkbox", "Чекбокс"),
                            ("radio", "Радиокнопка"),
                            ("select", "Выпадающий список"),
                            ("number", "Числовое поле"),
                            ("date", "Дата"),
                            ("range", "Диапазон"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Тип поля",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, verbose_name="Отображать в форме"
                    ),
                ),
                (
                    "is_searchable",
                    models.BooleanField(
                        default=True, verbose_name="Использовать для поиска"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False, verbose_name="Обязательное поле"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подсказка"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Для select, radio и checkbox. Формат: значение1=Текст1, значение2=Текст2",
                        verbose_name="Варианты выбора (через запятую)",
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Минимальное значение"
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Максимальное значение"
                    ),
                ),
                ("step", models.FloatField(blank=True, null=True, verbose_name="Шаг")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="search.searchconfig",
                        verbose_name="Конфигурация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поле поиска",
                "verbose_name_plural": "Поля поиска",
                "ordering": ["order"],
            },
        ),
    ]
