# Generated by Django 5.0 on 2026-02-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Текстовое поле"),
                    ("date_range", "Дата"),
                    ("range", "Интервал чисел"),
                    ("select", "Одинарный выбор"),
                    ("select_multiple", "Множественный выбор"),
                ],
                default="text",
                max_length=100,
                verbose_name="Тип поля",
            ),
        ),
    ]
