# Generated by Django 6.0.2 on 2026-03-26 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_alter_products_brand_alter_products_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_comment='Количество единиц товара в позиции корзины', default=1, help_text='Количество единиц товара в корзине', verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания позиции', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения позиции', verbose_name='Обновлено')),
                ('color', models.ForeignKey(db_comment='Внешний ключ на таблицу Colors', help_text='Выбранный цвет товара', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.colors', verbose_name='Цвет товара')),
                ('product', models.ForeignKey(db_comment='Внешний ключ на таблицу Products', help_text='Товар в корзине', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.products', verbose_name='Товар')),
                ('size', models.ForeignKey(db_comment='Внешний ключ на таблицу Sizes', help_text='Выбранный размер товара', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='products.sizes', verbose_name='Размер товара')),
                ('user', models.ForeignKey(db_comment='Внешний ключ на пользователя', help_text='Пользователь, которому принадлежит позиция корзины', on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
                'db_table_comment': 'Позиции товаров в корзине пользователей',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['user'], name='basket_user_idx'), models.Index(fields=['user', 'product'], name='basket_user_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product', 'size', 'color'), name='basket_user_product_size_color_uniq')],
            },
        ),
    ]
