# Generated by Django 5.0 on 2026-01-12 15:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="ID объекта, к которому привязан комментарий",
                        verbose_name="ID объекта",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя пользователя, оставившего комментарий",
                        max_length=100,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email пользователя (необязательно)",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст комментария (максимум 2000 символов)",
                        max_length=2000,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★☆☆☆☆ - Очень плохо"),
                            (2, "★★☆☆☆ - Плохо"),
                            (3, "★★★☆☆ - Средне"),
                            (4, "★★★★☆ - Хорошо"),
                            (5, "★★★★★ - Отлично"),
                        ],
                        default=0,
                        help_text="Оценка от 1 до 5 звезд",
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На модерации"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                            ("spam", "Спам"),
                        ],
                        default="pending",
                        help_text="Статус модерации комментария",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "admin_reply",
                    models.TextField(
                        blank=True,
                        help_text="Ответ администратора на комментарий",
                        max_length=2000,
                        verbose_name="Ответ администратора",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP адрес пользователя",
                        null=True,
                        verbose_name="IP адрес",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Информация о браузере пользователя",
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата ответа"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Редактировался"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Проверено"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=True, verbose_name="Анонимный"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные данные в формате JSON",
                        verbose_name="Метаданные",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Тип объекта, к которому привязан комментарий",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Авторизованный пользователь (если оставил комментарий)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovedComment",
            fields=[],
            options={
                "verbose_name": "Одобренный комментарий",
                "verbose_name_plural": "Одобренные комментарии",
                "proxy": True,
                "default_manager_name": "objects",
                "indexes": [],
                "constraints": [],
            },
            bases=("comments.comment",),
        ),
        migrations.CreateModel(
            name="PendingComment",
            fields=[],
            options={
                "verbose_name": "Комментарий на модерации",
                "verbose_name_plural": "Комментарии на модерации",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("comments.comment",),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="comments_co_content_cff8bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created_at"], name="comments_co_created_5f6a12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["rating"], name="comments_co_rating_ef6500_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["status"], name="comments_co_status_2720ea_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="comments_co_user_id_063857_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["email"], name="comments_co_email_7ec44a_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_verified"], name="comments_co_is_veri_7242c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 0), ("rating__lte", 5)),
                name="rating_range_check",
            ),
        ),
    ]
